[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm i -g bun && bun install"]

[phases.build]
cmds = ["bun run db:generate && npx prisma db push --skip-generate && bun run build"]

[start]
cmd = "node_modules/.bin/next start"
